
# Django settings for dury_app project.

# Generated by 'django-admin startproject' using Django 5.1.4.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.1/ref/settings/

from pathlib import Path
import os # Make sure this is imported

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3c(wb^vj@q8t3rikk)3a!i^w-ggm%oo(2-f#hyykpyo^gb)94i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'app.apps.AppConfig',
    'storages', # Still useful, many storage backends inherit from it
    'django_bunny_storage', # Your Bunny.net storage backend
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware", # Add this line
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dury_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dury_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# If you plan to use PostgreSQL in production, uncomment and configure this:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'duryapp',
#         'USER': 'postgres',
#         'PASSWORD': '132001',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # Good practice for collectstatic in production
# Set default storage for media files to BunnyStorage
# DEFAULT_FILE_STORAGE = 'django_bunny_storage.storage.BunnyStorage'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

# --- Cloudinary settings removed as you're switching to Bunny.net ---
# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': 'dhg8mqa6o',
#     'API_KEY': '339523357929551',
#     'API_SECRET': 'u5QlhL0CjtESQWKyyAjk3a6ZwRU',
# }
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage' # This line will be replaced by Bunny.net


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",    # React development server
    "https://your-production-domain.com",    # Your production frontend URL
]
CORS_ALLOW_ALL_ORIGINS = True # Be careful with this in production. Only use specific origins.


CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]


CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrftoken",
    "x-requested-with",
]


# -----------------------------------------------------------------
# Bunny.net Storage Configuration
# IMPORTANT: For production, use environment variables for BUNNY_USERNAME and BUNNY_PASSWORD.
# Never hardcode sensitive credentials in production!
BUNNY_USERNAME = os.environ.get('BUNNY_USERNAME', 'duryapp-videos') # Replace 'duryapp-videos' with your actual Storage Zone Name
BUNNY_PASSWORD = os.environ.get('BUNNY_PASSWORD', '9365a251-ff99-4eed-8c51ee77778f-3a72-4c42') # Replace with your actual Storage Zone Password (API Key)
BUNNY_REGION = os.environ.get('BUNNY_REGION', 'jh') # Replace 'jh' with your actual Storage Zone Region Code (e.g., 'de', 'ny', 'sg', 'jh')
BUNNY_PULL_ZONE_URL = os.environ.get('BUNNY_PULL_ZONE_URL', 'https://duryapp-cdn.b-cdn.net/') # Replace with your actual CDN Pull Zone Hostname (e.g., https://yourpullzonename.b-cdn.net/)


# MEDIA_URL should point to your CDN Pull Zone for files uploaded via Django's storage system
# Note: 'media/' will be a subfolder in your Bunny Storage Zone
MEDIA_URL = BUNNY_PULL_ZONE_URL



# Your existing STORAGES setting might look like this:
STORAGES = {
    # 'default' is for media files, which is already configured for Bunny.net
    "default": {
        "BACKEND": "django_bunny_storage.storage.BunnyStorage",
    },
    # Add this for static files:
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}